-- Delete investors with invalid country values
DELETE FROM public.investors 
WHERE country IN (
  'Tax planning',
  'Pension funds & pension funds',
  'Financial Services: We manage all matters related to assets, including taxes, legal issues, gifts, and estate planning.',
  'Family Office Services',
  'nan',
  'Public Equity: Investments in publicly traded companies.',
  'South Africa: Long/short portfolios focusing predominantly on South African equities, with an allocation to global emerging markets...',
  'Investment Advisory: Crafting and managing portfolios tailored to individual risk profiles, market conditions, and long-term goals.',
  'Reunion',
  'Investment Advisory',
  'Industry: Our industrial ventures include leading companies in precast concrete markets...',
  'Commercial properties, including retail, office, hotel, and multifamily assets.',
  'Financial Advisory: Mergers & acquisitions, divestitures, debt restructuring, and corporate and sovereign advisory.',
  'Financing, Facilities.',
  'Financial Advice: Tailored guidance to navigate your financial landscape.',
  'Manage investments',
  'Real Estate: Core real estate investments and developments in commercial and residential sectors.',
  'Financial Statements: Preparation and review of financial documents to ensure accuracy and compliance.',
  'Technology',
  'Technology-Driven Sourcing: Signal employs proprietary technology to identify investment opportunities.',
  'Asset Allocation: Developing robust investment strategies...',
  'Private Equity: We provide access to premier primary and secondary private equity opportunities...',
  'Private Equity: Long-term management of private equity assets with strategic and business development added value.',
  'Private Debt: Direct lending and asset-based finance.',
  'Independent Asset Management: Personalized and objective asset management solutions.',
  'trust system',
  'Software',
  'Family Office: Advisory, wealth solutions, and services tailored to entrepreneurs and their families.',
  'Legal and tax specialists create custom wealth strategies.',
  'Educating and involving family members, preparing the next generation and stakeholders.',
  'Geographical Focus: We invest in companies with compelling long-term prospects.',
  'South Korea: Portfolio management and discretionary mandates tailored to institutional and high-net-worth clients.',
  'Custody services and performance tracking.',
  'Legal Services: Assistance with corporate structuring, regulatory compliance, and contractual matters.',
  'Luxembourg: Private equity and real estate investment strategies serving institutional investors.',
  'Alternative Investments: Exposure to hedge funds, private equity, real estate, and commodities.',
  'Asia: Long-term strategic investments with value creation through operational enhancement.',
  'Strategic Holdings: Long-term capital allocation to transformative business opportunities.',
  ' South America: Sector-agnostic investments targeting scalable businesses.',
  'Company Building: Supporting ventures from inception to exit.',
  'Regulatory Oversight: Ensuring full compliance with international standards.',
  'Real Assets: Focus on infrastructure and natural resources.',
  'Wealth Planning: Succession, tax, and estate structuring tailored to families'' objectives.',
  'Africa: Growth equity investments in high-potential sectors.',
  'Sustainable Investing: ESG-focused strategies driving long-term value.',
  'Fixed Income: Diversified strategies across credit and duration.',
  'Germany: Sector-focused private equity across DACH region.',
  'Operational Support: Value-added services in scaling, recruitment, and governance.',
  'Middle East: High-growth opportunities in fintech, healthcare, and logistics.',
  'Dedicated teams across multiple jurisdictions.',
  ' Global Reach: Direct presence in 10+ international markets.',
  'Middle East and North Africa: Sector-specific growth capital.'
);