// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohiqolnendkhyuomdbnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oaXFvbG5lbmRraHl1b21kYm54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDQ2NzQsImV4cCI6MjA2MzY4MDY3NH0.0HcVrkFZb-FTyiytCz5RoQScxJevBoKNiMcJiJf-cY4";

// Enhanced Supabase client with improved timeout and error handling
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  },
  global: {
    headers: {
      'X-Client-Info': 'easyfund-web-v3-streamlined'
    },
    fetch: (url, options = {}) => {
      // Set a 15-second timeout to give faster feedback on server issues.
      // The error will be caught and handled by the auth submission logic.
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 15000);

      return fetch(url, {
        ...options,
        signal: controller.signal
      }).finally(() => {
        clearTimeout(timeoutId);
      });
    }
  }
});
